language: php

# lock distro so new future defaults will not break the build
dist: trusty

jobs:
  include:
    - php: 5.3
      dist: precise
    - php: 5.6
    - php: hhvm-3.18
  allow_failures:
    - php: hhvm-3.18

install:
  - composer install --prefer-source --no-interaction

script:
  - vendor/bin/phpunit --coverage-text
